apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonAnnotations:
#   argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

commonLabels:
  production: "true"

namespace: prod-eightknot

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: eightknot-app-server
    patch: |-
      - op: add
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: eightknot-worker-callback
    patch: |-
      - op: add
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: eightknot-worker-query
    patch: |-
      - op: add
        path: /spec/replicas
        value: 2
  - target:
      kind: HorizontalPodAutoscaler
    patch: |-
      - op: add
        path: /spec/minReplicas
        value: 2
  - target:
      kind: Ingress
      name: eightknot-app-server
    patch: |-
      - op: add
        path: /spec/rules/0/host
        value: eightknot.osci.io
  - target:
      kind: Namespace
      name: sandbox
    patch: |-
      - op: replace
        path: /metadata/annotations/openshift.io~1description
        value: "8Knot Production Deployment"
      - op: replace
        path: /metadata/annotations/openshift.io~1display-name
        value: "Production 8Knot"
      - op: replace
        path: /metadata/name
        value: "prod-sandiego-explorer-osci-io"
  - target:
      kind: Route
      name: eightknot-app-server
    patch: |-
      - op: add
        path: /spec/host
        value: eightknot.osci.io
  # TODO: fix init containers using image stream
  - target:
      kind: Deployment
      name: eightknot-app-server
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/image
        value: 'image-registry.openshift-image-registry.svc:5000/prod-eightknot/eightknot-app:latest'
