apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: eightknot-app
  app.kubernetes.io/component: eightknot-app
  app.kubernetes.io/instance: eightknot-app
  app.kubernetes.io/part-of: eightknot-app

resources:
  - 8k-app-server.yaml
  - 8k-autoscale.yaml
  - 8k-bc.yaml
  - 8k-redis.yaml
  - 8k-worker-callback.yaml
  - 8k-worker-query.yaml
  - 8k-redis-users.yaml
  - 8k-postgres-cache.yaml
  # - namespace.yaml
  - secret-augur.yaml
  - secret-redis.yaml
  - secret-postgres.yaml
